smartystreets/goconvey

goconvey.go

This makes goconvey's http server bind only to 127.0.0.1 by default, keeping
it from being exposed to the rest of the network.
Fixes #300

Pass the commandline host parameter to ListenAndServe

---

web/client/index.html
web/client/resources/css/themes/dark.css
web/client/resources/css/themes/light.css
web/client/resources/js/goconvey.js
web/client/resources/js/lib/ansispan.js

Some testing packages (such as goconvey itself) will colour the output with ANSI escape sequences; the web view will display them as, for example, "[32m✔[0m", which gets noisy very quickly. This patch converts them to span tags with colour classes.
This is based on https://github.com/mmalecki/ansispan

convert ansi colour sequences to coloured span tags

---

web/server/contract/result.go

My $GOPATH looks like: `~/src/go`
Which resulted in load errors like so:
```
2015/01/26 15:45:06 shell.go:93: Please run goconvey from within your $GOPATH (symlinks might be problematic). Output and Error:  can't load package: package go/src/github.com/me/mypackage: cannot find package "go/src/github.com/me/mypackage" in any of:
/usr/local/go/src/go/src/github.com/me/mypackage (from $GOROOT)
/Users/me/src/go/src/go/src/github.com/me/mypackage (from $GOPATH)
exit status 1
```
This makes the minor change of splitting on the same `endGoPath` token, then returning the last item.

change to GOPATH parsing for GOPATHs containing "src"

---

web/client/resources/js/goconvey.js

Using keydown instead of keyup insures that if ctrl/command is pushed down the shortcut won't proceed.

fixes issue: Cmd+C or Ctrl+C shouldn't open composer #252

---

web/server/watch/integration.go
web/server/watch/integration_test.go

Change watcher behavior to avoid unnecessary re-execution of tests.
- When a package is ignored, never re-execute
- When a package is reinstated, run tests unless the watcher is paused

Fix #310: Re-execute only when it makes sense

---

web/server/contract/contracts.go
web/server/contract/result.go
web/server/executor/coordinator.go
web/server/executor/tester.go
web/server/executor/tester_test.go
web/server/messaging/messages.go
web/server/system/shell.go
web/server/system/shell_integration_test.go
web/server/system/shell_test.go
web/server/watch/functional_core.go
web/server/watch/functional_core_test.go
web/server/watch/imperative_shell.go
web/server/watch/integration.go

This allows you to drop build -tags in the .goconvey file and have them correctly used by all the relevant go tool invocations. This is particularly useful for appengine go packages, which invariably need the bogus `+build appengine` build tag.

Parse tags option

---

convey/gotest/utils.go

This change came about because of a use case where the current semantics around resolving
external callers was not ideal.  The use case was for testing interfaces.  In such cases,
the interfaces are typically stored in one package while implementations are stored
in another.  Furthermore, tests written against the interface are stored with the interfaces
but the actual tests that instantiate the implementation and call the interface tests
are stored with the implementations.  The net result of this is that GoConvey would
get confused on who the external caller was AND any files that ended in _test.go stored
with the interfaces were excluded during compilation of the implementations.  This small
change allows files ending in _tests.go to also be candidates for external callers.  The
result …

Small change to include files that end in _tests.go as external callers

---

web/server/parser/packageParser.go
web/server/parser/package_parser_test.go

This change allows goconvey to execute with current tip. There are two other failures in the test suite that I didn't investigate. I believe they're related to the number of goroutines started to run tests.

Fixes for 1.5

---

web/client/index.html

Added iOS meta tag to index.html so that when creating a home screen
shortcut from Safari the browser chrome will be hidden, giving a better
experience for that scenario.

Add iOS META tag for full screen iOS Safari Home Screen bookmarks

---

web/server/watch/functional_core.go
web/server/watch/functional_core_test.go

Flymake is a widely used plugin for emacs. It checks regularly the unsaved code for errors. Therefore it creates e.g. a temporary file flymake_foo.go for foo.go. These temporary files trigger goconvey to test aflter almost every keystroke, which makes goconvey useless. This branch fixes it by ignoring flymake_* flies. It is only a very minimal patch but a welcome fix for the emacs users.

fix flymake (https://github.com/dougm/goflymake)

---

goconvey.go

Sorry. The sudden change in abstraction, from readable high to detailed low level inner loop was jarring. Couldn't help it. I refactored the out of place low level inner loop into a helper function. 7 lines now replaced with 1 thats readable and does the same thing.

Extract low level loop to helper function

---

README.md

This PR modifies the README:
Before
The README asked users to open their browser to localhost:8080
Now
The README asks user to 'watch' the tests display in their browser.  A link has been provided for when the browser doesn't automatically open.

Tell users. Browser opens automatically.

---

goconvey.go

Running Linux the browser launch command blocks until the browser is closed. This is very confusing and unhelpful behavior.

Fix browser opening blocking serveHTTP

---

web/client/resources/css/common.css

This also remove the auto-wrap. The output is now far easier to read, especially for verbose errors.
A preview, on top is the old version, below the new.

Remove height limit on errors

---

goconvey.go
web/server/watch/imperative_shell.go
web/server/watch/integration.go
web/server/watch/integration_test.go

A flag can be passed to goconvey to specify directories to be excluded
from being watched.  The default skipped directories are vendor and
node_modules.

added excluded directory functionality

---

convey/init.go

Provide a way to set the reporter using other methods than simply
command line flags. Passing flags to goconvey is iffy when working
with mixed tests, not all of which might use goconvey
(and unrecognized flags cause the test binary to fail)
---
Scenario:
* Have some test suites (from companion packages, etc) not using GoConvey
* running tests in a remote console CI environment which doesn't pass utf-8 back well, so I get back a bunch of question marks. 
* Want to use `-v` to show detailed testing, but also want `-story=false` to disable the dot reporter, but this doesn't work out because any packages not using goconvey will fail with invalid flag passed

Add env var to configure goconvey reporter.

---

web/client/resources/js/goconvey.js

‘array’ is not a possible return value of the typeof function.
typeof(arrayVal) returns ‘object’
typeof val === ‘object’ will catch all values that are arrays.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operat
ors/typeof

Fix 'Invalid typeof comparison value'

---

convey/reporting/init.go

Using tmux, `$TERM` is `screen-256color` as default.
In `screen-256color`, that can display colored output but go-convey allows `xterm-*` only.
So I fixed `isXterm` function to `isColorableTerminal` that allows any `$TERM` containing "color".

Support screen-256color

---

convey/init.go
web/server/system/shell.go
web/server/system/shell_test.go

I believe I've fixed all places you mentioned in #386 , but could you take a look?

prefix "convey" added to all command line flags #386

---

goconvey.go

Follow-up to #412. No real functionality change, just prevents a panic in the output.

Exit if port is in use instead of allowing a panic

---

convey/reporting/statistics.go

This fixes #234, the immediate data race issue, by locking around the
members of the global statistics struct. It doesn't address the issue of
tests stomping on each others' colors, indentation, and other output.

Add locking to report statistics.

---

web/client/resources/js/goconvey.js

#413 Mentioned an issue I had noticed.  Needed to re-run tipsy creation when new markup is generated. The ultimate cause being that newer versions of jquery no longer support the 'live' option.  
See: http://stackoverflow.com/questions/15473731/tipsy-live-does-not-work-with-jquery-1-9-0 for more details about the issue.

Fix #413 - this[binder] issue with tipsy and newer versions of jQuery.

---

README.md

The last three links in the menu were broken because the headings were missing.

Fix readme TOC links and headers

---

goconvey.go

When flag is false no browser launch is attempted.
useful if your on a remote host and don't want firefox launching via an
X forward.

Added a new flag launchBrowser defaulted to true

---

web/client/index.html
web/client/resources/js/goconvey.js

Added configuration to notifications based on test result status as was discussed in issue #406 
Screen-capture Preview:

Fix #406 - Settings for notify by a given level

---

web/client/resources/js/goconvey.js

With low coverage there's a small cosmetic bug that shows up:

Fix rendering bug with low coverage

---

web/server/watch/imperative_shell.go

This PR skips directories starting with `.` to dramatically improve performance if such directories are present. It's a small change but makes a huge impact when there's a directory (such as artifacts from a build tool -- in my case Wercker -- as a hidden directories in the working dir).
Profiled using [pkg/profile](https://github.com/pkg/profile):
**Before**
```
$ go tool pprof --text ./goconvey /var/folders/8m/dzjlyrtd3vx3hb0mwfxgswm80000gn/T/profile152855215/cpu.pprof
42.83s of 43.63s total (98.17%)
Dropped 105 nodes (cum <= 0.22s)
flat  flat%   sum%        cum   cum%
14.42s 33.05% 33.05%     14.42s 33.05%  syscall.Syscall
9.10s 20.86% 53.91%      9.11s 20.88%  syscall.Syscall6
6.57s 15.06% 68.97%      6.57s 15.06%  runtime.mach_semaphore_wait
6.48s 14.85% 83.82%      6.48s 14.85% …
```

Improve performance by skipping hidden dirs

---

web/server/parser/packageParser.go
web/server/parser/package_parser_test.go

Minimal PR to have subtests correctly showing on the web interface. This addresses #429 (and #440).

Add support for Go 1.7 subtests

---

convey/assertions.go

This commit along with https://github.com/smartystreets/assertions/pull/16 will add the `ShouldBeError` assertion to Goconvey.

Added ShouldBeError assertion

---

web/server/parser/rules.go

In Go 1.9 reporting for empty packages (directories without any .go files) has changed from "no Go source files in" to "no Go files in". This patch extends parsing rules to match this behaviour.

Fix Go1.9 empty package detection rules

---

web/server/system/shell.go

This should fix bug with only one test file that is in an external test package (e.g. `package_test`) or a possible situation whether there are multiple test files in mixed packages, but unique imports from external test package don't get fetched leading to empty list.

Add XTestImports to go list arguments

---

web/server/parser/rules.go

go 1.11 has changed the error message. 
the message looks like this 
```
can't load package: package github.com/0nedark/serv/src: unknown import path "github.com/0nedark/serv/src": cannot find module providing package github.com/0nedark/serv/src
```
This PR fixes this problem.

handle error message when no go files exists for go 1.11

---

goconvey.go

Fixes launching web browser when `GOOS` is `windows` (which is the `GOOS` used on Windows, rather than `win32`). As seen here:
```text
...
2018/07/25 19:59:09 goconvey.go:194: Serving HTTP at: http://127.0.0.1:8080
2018/07/25 19:59:09 goconvey.go:103: Skipped launching browser for this OS: windows
...
```

Open web browser on windows

---

go.mod
go.sum

That would be nice to add Go modules support to this repo, so for those who already started dealing with `go mod` it'll be a little bit simpler to deal with goconvey.
I didn't make any manual fixes here. I simply called two commands to prepare this PR:
- `GO111MODULE=on go mod init` to create a general go,mod file
- `GO111MODULE=on go mod tidy` to get the list of dependencies of the project
Thanks!

Introducing go mod (or "go modules", or "vgo")

---

convey/reporting/init.go
convey/reporting/problems.go

Sometimes I want to reuse some parts of the test code and this might lead to multiple nested levels of functions. In this case tracing the line where the test is failed is time consuming without the stack trace. So I adding stack trace to make this process faster.

Add stack trace for failed test

---

go.mod
go.sum
goconvey.go
goconvey_1_8.go
goconvey_1_9.go
web/server/contract/result.go

Currently, GoConvey uses go/build and `build.ImportDir()` to collect
information about a package, including its name. Under modules that
live outside of the GOPATH, this resolution breaks, and every module
ends up with the name ".". At the very least this breaks coverage by
causing all coverage reports to be written to client/reports.html
instead of client/reports/<opackage specific>.html.
The core issue is the go/build does not fully support modules. There
was a partial fix submitted in https://github.com/golang/go/commit/f85125345cc5d3eb054c90bfca4bda3544d7fcab,
but it only works if the package being looked up is being looked up by
name, not by path, and GoConvey somewhat necessarily uses the path. As
outlined in the above commit, the intended solution is to use the …

Correctly identify package names in modules

---

convey/doc.go
convey/reporting/init.go

Hi, we updated some exported function comments based on best practices from Effective Go. It’s admittedly a relatively minor fix up. Does this help you?

Fix function comments based on best practices from Effective Go

---

web/server/parser/packageParser.go
web/server/parser/package_parser_test.go

Fixes: https://github.com/smartystreets/goconvey/issues/487
Cc: @JoyPeterson, @homanchou

Add code for parsing format that ginkgo tests emit

---

web/server/system/shell.go
web/server/system/shell_1_16.go
web/server/system/shell_older_than_1_16.go

`go test -i` is deprecated in go 1.16, and it makes the output parsing
fail, leading to to no coverage reported.
closes https://github.com/smartystreets/goconvey/issues/613

Define a new compile func for go 1.16

---

goconvey.go

Go tooling, including `go test` treat the testdata directory as an opaque
directory containing data for tests. Unfortunately, goconvey would treat go
source files inside testdata or its subdirectories as creating a package,
causing divergence in behavior from Go tooling.
This commit causes goconvey to not treat anything inside the testdata
directory or subdirectories as a package without removing them from the watch
list. This creates behavioral parity with Go tooling, but means a change in
testdata will still cause tests to be rerun.

Stop compiling and testing packages in testdata

---

CONTRIBUTING.md
README.md
web/client/index.html

The first time I clicked it, I was HTTP 302 redirected to a fake malware scanner, but every subsequent time I was redirected to a seeming blank page under the goconvey.co domain.
This change simply removes all refererces to http://goconvey.co

Remove references to http://goconvey.co as malware squatters appear to have taken it

---

README.md

detail:
Deprecation of 'go get' for installing executables https://docs.studygolang.com/doc/go-get-install-deprecation

fix document about "go get"

---

web/server/watch/functional_core.go
web/server/watch/functional_core_test.go

Add global .goconvey as https://github.com/smartystreets/goconvey/issues/620

added main.goconvey

---

web/client/index.html

See https://github.com/smartystreets/goconvey/issues/684
Before:
After:

fix(web): protect against XSS in test description

---

convey/stack_trace_test.go
web/server/parser/packageParser.go
web/server/parser/package_parser_test.go
web/server/watch/integration_testing/sub/.gitignore

one of these tests double-counted goroutines, because logging output now includes "goroutine" twice. This looks for just the first instance.
the other test failed on test instances which used multiple "%" signs after coverage numbers. It works with this change, and IMO it's simpler than it was as well.
also update a gitignore to use a correct new path

fix: fix a few tests that were broken at HEAD

---

web/server/watch/integration.go
web/server/watch/integration_test.go

These integration tests were very flaky before. Running them repeatedly, e.g. by `while true; do go test -count=1 ./web/server/watch; done`, would lead to different errors each time on assertions about watcher results outputs.
I traced this back to integration.go's Watcher.Listen(). This function is designed to loop forever, each time looking for changes in the local filesystem, then responding if it does find changes. It's all really janky, to be honest. The problem here was that the tests were very sensitive to when input commands came in. If the recipient got two commands quickly, then you'd have the two commands processed before a scan could happen (in the select's default case). With this change, the select will always do a scan after each command is run, and it also won't sleep …

fix(web): fix nondeterministic tests
